package dari.entity;

public enum AnnonceRegion {
	TUNIS,ARIANA,SOUSSE,MANOUBA, BEN_AROUS, ZAGHOUAN, SFAX ,MONASTIR,MAHDIA,NABEL,BIZERTE,GABES,MEDNINE,TATAOUINE,KEBILI,TOUZEUR,GAFSA,KASSERINE,SIDI_BOUZID,KAIROUAN,KEF,SELIENA,JANDOUBA,BEJA


}
